import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:UniSync/features/interview/repository/interview_admin_repository.dart';
import 'package:UniSync/features/interview/view/interview_palette.dart';

InterviewPalette _ui(BuildContext context) => InterviewPalette.of(context);

class InterviewAdminPanelScreen extends StatefulWidget {
  const InterviewAdminPanelScreen({super.key});

  @override
  State<InterviewAdminPanelScreen> createState() =>
      _InterviewAdminPanelScreenState();
}

class _InterviewAdminPanelScreenState extends State<InterviewAdminPanelScreen> {
  static const JsonEncoder _prettyEncoder = JsonEncoder.withIndent('  ');

  final InterviewAdminRepository _repo = InterviewAdminRepository();

  final TextEditingController _templateJsonController = TextEditingController();
  final TextEditingController _domainJsonController = TextEditingController();
  final TextEditingController _sessionUserIdController =
      TextEditingController();
  final TextEditingController _sessionTemplateIdController =
      TextEditingController();
  final TextEditingController _sessionOutputController =
      TextEditingController();

  bool _isTemplateBusy = false;
  bool _isDomainBusy = false;
  bool _isSessionBusy = false;

  List<_ActionLog> _templateLogs = const [];
  List<_ActionLog> _domainLogs = const [];
  int _sessionCount = 0;

  @override
  void initState() {
    super.initState();
    _templateJsonController.text = _prettyEncoder.convert({
      'templates': [
        {
          'title': 'Flutter BLoC Interview Template',
          'domain': 'flutter',
          'icon': 'https://cdn.example.com/icons/flutter.png',
          'topics': ['bloc basics', 'state management', 'streams'],
          'evaluationMetrics': [
            {
              'topic': 'bloc proficiency',
              'description':
                  'Ability to implement Bloc pattern with proper events and states',
            },
          ],
          'coinPrice': 10,
        },
      ],
    });

    _domainJsonController.text = _prettyEncoder.convert({
      'domains': [
        {
          'domain': 'flutter',
          'subDomains': [
            {
              'label': 'BLoC',
              'logo': 'https://cdn.example.com/logos/bloc.png',
            },
          ],
        },
      ],
    });
  }

  @override
  void dispose() {
    _templateJsonController.dispose();
    _domainJsonController.dispose();
    _sessionUserIdController.dispose();
    _sessionTemplateIdController.dispose();
    _sessionOutputController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _ui(context).backgroundPrimary,
      appBar: AppBar(
        title: const Text(
          'Interview Admin Panel',
          style: TextStyle(fontWeight: FontWeight.w700),
        ),
      ),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 28),
          children: [
            _buildContractCard(),
            const SizedBox(height: 12),
            _buildTemplateCard(),
            const SizedBox(height: 12),
            _buildDomainCard(),
            const SizedBox(height: 12),
            _buildInterviewReadCard(),
          ],
        ),
      ),
    );
  }

  Widget _buildContractCard() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _ui(context).backgroundSecondary,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: _ui(context).borderSubtle),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Production Contract',
            style: TextStyle(
              color: _ui(context).textPrimary,
              fontWeight: FontWeight.w700,
            ),
          ),
          SizedBox(height: 6),
          Text(
            'Template write endpoints: POST/PATCH /api/carrer/template',
            style: TextStyle(color: _ui(context).textSecondary, fontSize: 12),
          ),
          Text(
            'Domain write endpoints: POST /api/domain/createDomains and /api/domain/:domain/subdomains',
            style: TextStyle(color: _ui(context).textSecondary, fontSize: 12),
          ),
          Text(
            'Interview sessions are generated by socket flow; panel exposes read-only session lookup.',
            style: TextStyle(color: _ui(context).textSecondary, fontSize: 12),
          ),
        ],
      ),
    );
  }

  Widget _buildTemplateCard() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _ui(context).backgroundSecondary,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: _ui(context).borderSubtle),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Template Seeder (JSON)',
            style: TextStyle(
              color: _ui(context).textPrimary,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 10),
          _buildJsonInput(
            controller: _templateJsonController,
            hint: 'Paste template JSON here',
            minLines: 8,
            maxLines: 18,
          ),
          const SizedBox(height: 10),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: [
              ElevatedButton.icon(
                onPressed: _isTemplateBusy ? null : _loadTemplatesIntoEditor,
                icon: const Icon(Icons.download_rounded, size: 16),
                label: const Text('Load Current'),
              ),
              ElevatedButton.icon(
                onPressed: _isTemplateBusy ? null : _importTemplates,
                icon: _isTemplateBusy
                    ? SizedBox(
                        width: 14,
                        height: 14,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: _ui(context).buttonPrimaryFg,
                        ),
                      )
                    : const Icon(Icons.upload_rounded, size: 16),
                label: Text(_isTemplateBusy ? 'Importing...' : 'Import JSON'),
              ),
            ],
          ),
          const SizedBox(height: 10),
          _buildLogList(_templateLogs),
        ],
      ),
    );
  }

  Widget _buildDomainCard() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _ui(context).backgroundSecondary,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: _ui(context).borderSubtle),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Domain Seeder (JSON)',
            style: TextStyle(
              color: _ui(context).textPrimary,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 10),
          _buildJsonInput(
            controller: _domainJsonController,
            hint: 'Paste domain JSON here',
            minLines: 6,
            maxLines: 16,
          ),
          const SizedBox(height: 10),
          ElevatedButton.icon(
            onPressed: _isDomainBusy ? null : _importDomains,
            icon: _isDomainBusy
                ? SizedBox(
                    width: 14,
                    height: 14,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      color: _ui(context).buttonPrimaryFg,
                    ),
                  )
                : const Icon(Icons.cloud_upload_rounded, size: 16),
            label: Text(_isDomainBusy ? 'Importing...' : 'Import JSON'),
          ),
          const SizedBox(height: 10),
          _buildLogList(_domainLogs),
        ],
      ),
    );
  }

  Widget _buildInterviewReadCard() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: _ui(context).backgroundSecondary,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: _ui(context).borderSubtle),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Interview Session Lookup',
            style: TextStyle(
              color: _ui(context).textPrimary,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 8),
          TextField(
            controller: _sessionUserIdController,
            style: TextStyle(color: _ui(context).textPrimary),
            decoration: const InputDecoration(
              labelText: 'User ID',
              hintText: 'Firebase uid',
            ),
          ),
          const SizedBox(height: 8),
          TextField(
            controller: _sessionTemplateIdController,
            style: TextStyle(color: _ui(context).textPrimary),
            decoration: const InputDecoration(
              labelText: 'Template ID',
              hintText: 'Mongo template _id',
            ),
          ),
          const SizedBox(height: 8),
          ElevatedButton.icon(
            onPressed: _isSessionBusy ? null : _loadInterviewSessions,
            icon: _isSessionBusy
                ? SizedBox(
                    width: 14,
                    height: 14,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      color: _ui(context).buttonPrimaryFg,
                    ),
                  )
                : const Icon(Icons.search_rounded, size: 16),
            label: Text(_isSessionBusy ? 'Loading...' : 'Fetch Sessions'),
          ),
          const SizedBox(height: 8),
          Text(
            'Count: $_sessionCount',
            style: TextStyle(
              color: _ui(context).textSecondary,
              fontSize: 12,
            ),
          ),
          const SizedBox(height: 8),
          _buildJsonInput(
            controller: _sessionOutputController,
            hint: 'Session JSON output',
            minLines: 4,
            maxLines: 14,
            readOnly: true,
          ),
        ],
      ),
    );
  }

  Widget _buildJsonInput({
    required TextEditingController controller,
    required String hint,
    required int minLines,
    required int maxLines,
    bool readOnly = false,
  }) {
    return TextField(
      controller: controller,
      minLines: minLines,
      maxLines: maxLines,
      readOnly: readOnly,
      style: TextStyle(
        color: _ui(context).textPrimary,
        fontFamily: 'monospace',
        fontSize: 12,
      ),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: TextStyle(color: _ui(context).textMuted),
      ),
    );
  }

  Widget _buildLogList(List<_ActionLog> logs) {
    if (logs.isEmpty) {
      return Text(
        'No operations yet.',
        style: TextStyle(color: _ui(context).textMuted, fontSize: 12),
      );
    }

    return Column(
      children: logs
          .map(
            (log) => Container(
              margin: const EdgeInsets.only(bottom: 8),
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: log.success
                    ? _ui(context).success.withOpacity(0.12)
                    : _ui(context).error.withOpacity(0.12),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(
                  color: log.success
                      ? _ui(context).success.withOpacity(0.4)
                      : _ui(context).error.withOpacity(0.4),
                ),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    log.success ? Icons.check_circle : Icons.error,
                    size: 16,
                    color: log.success
                        ? _ui(context).success
                        : _ui(context).error,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      '${log.item}: ${log.message}',
                        style: TextStyle(
                        color: _ui(context).textPrimary,
                        fontSize: 12,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          )
          .toList(),
    );
  }

  Future<void> _loadTemplatesIntoEditor() async {
    setState(() {
      _isTemplateBusy = true;
      _templateLogs = const [];
    });

    try {
      final templates = await _repo.getTemplatesRaw();
      if (!mounted) return;
      _templateJsonController.text = _prettyEncoder.convert({
        'templates': templates,
      });
      setState(() {
        _templateLogs = [
          _ActionLog(
            item: 'Templates',
            success: true,
            message: 'Loaded ${templates.length} records from backend',
          ),
        ];
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _templateLogs = [
          _ActionLog(
            item: 'Templates',
            success: false,
            message: _errorMessage(e),
          ),
        ];
      });
    } finally {
      if (!mounted) return;
      setState(() => _isTemplateBusy = false);
    }
  }

  Future<void> _importTemplates() async {
    setState(() {
      _isTemplateBusy = true;
      _templateLogs = const [];
    });

    final logs = <_ActionLog>[];

    try {
      final payloads =
          _parseTemplatePayload(_templateJsonController.text.trim());
      for (var i = 0; i < payloads.length; i++) {
        final payload = Map<String, dynamic>.from(payloads[i]);
        final id = (payload.remove('_id') ?? '').toString().trim();
        final title = (payload['title'] ?? 'template_${i + 1}').toString();

        try {
          if (id.isEmpty) {
            _validateCreateTemplate(payload, i + 1);
            await _repo.createTemplate(payload);
            logs.add(
              _ActionLog(
                item: title,
                success: true,
                message: 'Created',
              ),
            );
          } else {
            if (payload.isEmpty) {
              throw FormatException('No update fields provided');
            }
            await _repo.updateTemplate(id, payload);
            logs.add(
              _ActionLog(
                item: '$title ($id)',
                success: true,
                message: 'Updated',
              ),
            );
          }
        } catch (e) {
          logs.add(
            _ActionLog(
              item: title,
              success: false,
              message: _errorMessage(e),
            ),
          );
        }
      }
    } catch (e) {
      logs.add(
        _ActionLog(
          item: 'Template JSON',
          success: false,
          message: _errorMessage(e),
        ),
      );
    } finally {
      if (!mounted) return;
      setState(() {
        _templateLogs = logs;
        _isTemplateBusy = false;
      });
    }
  }

  Future<void> _importDomains() async {
    setState(() {
      _isDomainBusy = true;
      _domainLogs = const [];
    });

    final logs = <_ActionLog>[];

    try {
      final payloads = _parseDomainPayload(_domainJsonController.text.trim());
      for (var i = 0; i < payloads.length; i++) {
        final item = payloads[i];
        final domain = item['domain'] as String;
        final subDomains =
            (item['subDomains'] as List).cast<Map<String, dynamic>>();

        try {
          final createResult = await _repo.createDomain(domain);
          final message = (createResult['message'] ?? '').toString();
          var finalMessage =
              message.isEmpty ? 'Domain request sent' : message.trim();

          if (subDomains.isNotEmpty) {
            final subResult = await _repo.addSubDomains(domain, subDomains);
            final subMessage = (subResult['message'] ?? '').toString().trim();
            if (subMessage.isNotEmpty) {
              finalMessage = '$finalMessage. $subMessage';
            } else {
              finalMessage =
                  '$finalMessage. Added ${subDomains.length} subdomains';
            }
          }

          logs.add(
            _ActionLog(
              item: domain,
              success: true,
              message: finalMessage,
            ),
          );
        } catch (e) {
          logs.add(
            _ActionLog(
              item: domain,
              success: false,
              message: _errorMessage(e),
            ),
          );
        }
      }
    } catch (e) {
      logs.add(
        _ActionLog(
          item: 'Domain JSON',
          success: false,
          message: _errorMessage(e),
        ),
      );
    } finally {
      if (!mounted) return;
      setState(() {
        _domainLogs = logs;
        _isDomainBusy = false;
      });
    }
  }

  Future<void> _loadInterviewSessions() async {
    final userId = _sessionUserIdController.text.trim();
    final templateId = _sessionTemplateIdController.text.trim();

    if (userId.isEmpty || templateId.isEmpty) {
      setState(() {
        _sessionCount = 0;
        _sessionOutputController.text = 'userId and templateId are required';
      });
      return;
    }

    setState(() => _isSessionBusy = true);
    try {
      final sessions = await _repo.getInterviewSessions(
        userId: userId,
        templateId: templateId,
      );
      if (!mounted) return;
      setState(() {
        _sessionCount = sessions.length;
        _sessionOutputController.text = _prettyEncoder.convert({
          'count': sessions.length,
          'data': sessions,
        });
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _sessionCount = 0;
        _sessionOutputController.text = _errorMessage(e);
      });
    } finally {
      if (!mounted) return;
      setState(() => _isSessionBusy = false);
    }
  }

  List<Map<String, dynamic>> _parseTemplatePayload(String raw) {
    if (raw.isEmpty) {
      throw const FormatException('Template JSON cannot be empty');
    }

    final decoded = jsonDecode(raw);
    final items = _extractItems(decoded, 'templates');
    if (items.isEmpty) {
      throw const FormatException('No templates found in JSON');
    }

    return List<Map<String, dynamic>>.generate(
      items.length,
      (index) => _normalizeTemplate(
        items[index],
        index + 1,
      ),
    );
  }

  List<Map<String, dynamic>> _parseDomainPayload(String raw) {
    if (raw.isEmpty) {
      throw const FormatException('Domain JSON cannot be empty');
    }

    final decoded = jsonDecode(raw);
    final items = _extractItems(decoded, 'domains');
    if (items.isEmpty) {
      throw const FormatException('No domains found in JSON');
    }

    return List<Map<String, dynamic>>.generate(
      items.length,
      (index) => _normalizeDomain(
        items[index],
        index + 1,
      ),
    );
  }

  List<Map<String, dynamic>> _extractItems(dynamic decoded, String listKey) {
    if (decoded is List) {
      return decoded.whereType<Map>().map(_toTypedMap).toList();
    }

    if (decoded is Map) {
      final typed = _toTypedMap(decoded);
      final listCandidate = typed[listKey];
      if (listCandidate is List) {
        return listCandidate.whereType<Map>().map(_toTypedMap).toList();
      }
      return [typed];
    }

    throw const FormatException('JSON must be an object or array');
  }

  Map<String, dynamic> _normalizeTemplate(Map<String, dynamic> raw, int index) {
    final normalized = <String, dynamic>{};

    final id = _readString(raw['_id'] ?? raw['id']);
    if (id.isNotEmpty) normalized['_id'] = id;

    final title = _readString(raw['title']);
    final domain = _readString(raw['domain']);
    final icon = _readString(raw['icon']);

    if (title.isNotEmpty) normalized['title'] = title;
    if (domain.isNotEmpty) normalized['domain'] = domain;
    if (icon.isNotEmpty) normalized['icon'] = icon;

    if (raw.containsKey('topics')) {
      normalized['topics'] = _normalizeStringList(raw['topics']);
    }

    if (raw.containsKey('evaluationMetrics')) {
      final metrics = raw['evaluationMetrics'];
      if (metrics is! List) {
        throw FormatException(
          'Template #$index: evaluationMetrics must be a list',
        );
      }
      normalized['evaluationMetrics'] = metrics.map((e) {
        if (e is! Map) {
          throw FormatException(
            'Template #$index: each evaluationMetrics item must be an object',
          );
        }
        final metricMap = _toTypedMap(e);
        final topic = _readString(metricMap['topic']);
        final description = _readString(metricMap['description']);
        if (topic.isEmpty || description.isEmpty) {
          throw FormatException(
            'Template #$index: metric topic and description are required',
          );
        }
        return {
          'topic': topic,
          'description': description,
        };
      }).toList();
    }

    if (raw.containsKey('coinPrice')) {
      final coinPrice = _parseCoinPrice(raw['coinPrice'], index);
      normalized['coinPrice'] = coinPrice;
    }

    return normalized;
  }

  Map<String, dynamic> _normalizeDomain(Map<String, dynamic> raw, int index) {
    final domain = _readString(raw['domain']);
    if (domain.isEmpty) {
      throw FormatException('Domain #$index: "domain" is required');
    }

    final normalized = <String, dynamic>{
      'domain': domain.toLowerCase(),
      'subDomains': <Map<String, dynamic>>[],
    };

    if (raw.containsKey('subDomains')) {
      final subDomains = raw['subDomains'];
      if (subDomains is! List) {
        throw FormatException('Domain #$index: subDomains must be a list');
      }

      normalized['subDomains'] = subDomains.map((e) {
        if (e is! Map) {
          throw FormatException(
            'Domain #$index: each subDomains item must be an object',
          );
        }
        final subDomain = _toTypedMap(e);
        final label = _readString(subDomain['label']);
        final logo = _readString(subDomain['logo']);
        if (label.isEmpty || logo.isEmpty) {
          throw FormatException(
            'Domain #$index: subDomain label and logo are required',
          );
        }
        return {
          'label': label,
          'logo': logo,
        };
      }).toList();
    }

    return normalized;
  }

  void _validateCreateTemplate(Map<String, dynamic> payload, int index) {
    final title = _readString(payload['title']);
    final domain = _readString(payload['domain']);
    final icon = _readString(payload['icon']);
    if (title.isEmpty || domain.isEmpty || icon.isEmpty) {
      throw FormatException(
        'Template #$index: title, domain, icon are required for create',
      );
    }
  }

  List<String> _normalizeStringList(dynamic value) {
    if (value is List) {
      return value
          .map((e) => _readString(e))
          .where((e) => e.isNotEmpty)
          .toList();
    }
    if (value is String) {
      return value
          .split(',')
          .map((e) => e.trim())
          .where((e) => e.isNotEmpty)
          .toList();
    }
    throw const FormatException('Expected a list of strings');
  }

  num _parseCoinPrice(dynamic value, int index) {
    if (value is num) {
      if (value < 0) {
        throw FormatException('Template #$index: coinPrice cannot be negative');
      }
      return value;
    }

    final parsed = num.tryParse(_readString(value));
    if (parsed == null || parsed < 0) {
      throw FormatException('Template #$index: coinPrice must be a number');
    }
    return parsed;
  }

  Map<String, dynamic> _toTypedMap(Map<dynamic, dynamic> map) {
    return Map<String, dynamic>.from(map);
  }

  String _readString(dynamic value) {
    if (value == null) return '';
    return value.toString().trim();
  }

  String _errorMessage(Object error) {
    if (error is FormatException) {
      return error.message.toString();
    }
    if (error is DioException) {
      final response = error.response?.data;
      if (response is Map && response['message'] != null) {
        return response['message'].toString();
      }
      return error.message ?? 'Network error';
    }
    return error.toString();
  }
}

class _ActionLog {
  const _ActionLog({
    required this.item,
    required this.success,
    required this.message,
  });

  final String item;
  final bool success;
  final String message;
}






